In [3]:
import pandas as pd
df = pd.read_csv("AuditLog_2020-07-28_2020-08-03.csv")
df

CreationDate                                 UserIds  \
0      2020-08-03T05:57:22.0000000Z  arq-member@androbotics.onmicrosoft.com   
1      2020-08-03T06:04:17.0000000Z  arn-member@androbotics.onmicrosoft.com   
2      2020-08-03T06:04:17.0000000Z  arn-member@androbotics.onmicrosoft.com   
3      2020-08-03T06:19:47.0000000Z                  s.ida@ml.androbo.co.jp   
4      2020-08-03T06:19:58.0000000Z                  s.ida@ml.androbo.co.jp   
...                             ...                                     ...   
30821  2020-07-28T22:49:03.0000000Z  aro-member@androbotics.onmicrosoft.com   
30822  2020-07-28T22:49:03.0000000Z  aro-member@androbotics.onmicrosoft.com   
30823  2020-07-28T15:20:15.0000000Z                          app@sharepoint   
30824  2020-07-28T15:26:36.0000000Z                          app@sharepoint   
30825  2020-07-28T15:28:21.0000000Z                          app@sharepoint   

                 Operations                                          AuditData  
0              UserLoggedIn  {"CreationTime":"2020-08-03T05:57:22","Id":"35...  
1              UserLoggedIn  {"CreationTime":"2020-08-03T06:04:17","Id":"4e...  
2              UserLoggedIn  {"CreationTime":"2020-08-03T06:04:17","Id":"9e...  
3      FileSyncUploadedFull  {"CreationTime":"2020-08-03T06:19:47","Id":"f0...  
4               FileRenamed  {"CreationTime":"2020-08-03T06:19:58","Id":"7c...  
...                     ...                                                ...  
30821       CompanyLinkUsed  {"CreationTime":"2020-07-28T22:49:03","Id":"d7...  
30822          FileAccessed  {"CreationTime":"2020-07-28T22:49:03","Id":"62...  
30823          FileAccessed  {"CreationTime":"2020-07-28T15:20:15","Id":"6c...  
30824          FileAccessed  {"CreationTime":"2020-07-28T15:26:36","Id":"f7...  
30825          FileAccessed  {"CreationTime":"2020-07-28T15:28:21","Id":"67...  

[30826 rows x 4 columns]

In [7]:
df["UserIds"]

0        arq-member@androbotics.onmicrosoft.com
1        arn-member@androbotics.onmicrosoft.com
2        arn-member@androbotics.onmicrosoft.com
3                        s.ida@ml.androbo.co.jp
4                        s.ida@ml.androbo.co.jp
                          ...                  
30821    aro-member@androbotics.onmicrosoft.com
30822    aro-member@androbotics.onmicrosoft.com
30823                            app@sharepoint
30824                            app@sharepoint
30825                            app@sharepoint
Name: UserIds, Length: 30826, dtype: object

In [11]:
df.groupby("Operations")

In [12]:
df["Operations"].unique()

array(['UserLoggedIn', 'FileSyncUploadedFull', 'FileRenamed',
       'FileAccessed', 'FileModifiedExtended', 'FileModified',
       'FilePreviewed', 'FileMoved', 'FileAccessedExtended',
       'Update device.', 'FolderCreated', 'PageViewed', 'FolderDeleted',
       'AnonymousLinkUsed', 'ListViewed', 'FileDeleted',
       'CompanyLinkUsed', 'SharingSet', 'AddedToGroup',
       'CompanyLinkCreated', 'Get-CsTeamsClientConfiguration',
       'GroupAdded', 'SharingInheritanceBroken', 'FileUploaded',
       'FileDownloaded', 'PagePrefetched', 'PageViewedExtended',
       'FileSyncDownloadedFull', 'Update', 'SoftDelete',
       'TeamsSessionStarted', 'MoveToDeletedItems', 'Add user.',
       'UserLoginFailed', 'ViewResponses', 'ListForms', 'ViewForm',
       'HardDelete', 'ModifyFolderPermissions', 'FolderMoved', 'Set-User',
       'Add member to group.', 'FolderRenamed', 'MemberAdded',
       'ListCreated', 'Update user.', 'Remove member from group.',
       'UpdateInboxRules', 'FolderCopied

In [1]:
import pandas as pd
import numpy as np

# スカラー

In [ ]:
1　[1]

# ベクトル

In [4]:
a = [1,5] 
b = [1,5,6,8,9]

c = [
    1,
    2,
    3,
    4,
    5
]


# 行列

In [25]:
d = [
    [1,2,3,4,5],
    [5,7,9,8,0],
    [4,9,7,8,9]
    ]

e = [
    [1,5,4,5,9],
    [2,7,9,7,6],
    [3,9,7,4,7]
    ]

In [26]:
d*e

TypeError: can't multiply sequence by non-int of type 'list'

In [23]:
d*2

[[1, 2, 3, 4, 5],
 [5, 7, 9, 8, 0],
 [4, 9, 7, 8, 9],
 [1, 2, 3, 4, 5],
 [5, 7, 9, 8, 0],
 [4, 9, 7, 8, 9]]

In [18]:
d+e

[[1, 2, 3, 4, 5],
 [5, 7, 9, 8, 0],
 [4, 9, 7, 8, 9],
 [1, 5, 4, 5, 9],
 [2, 7, 9, 7, 6],
 [3, 9, 7, 4, 7]]

In [7]:
a = np.array([
    [1,2,3,4,5],
    [5,7,9,8,0],
    [4,9,7,8,9]
    ])
a

array([[1, 2, 3, 4, 5],
       [5, 7, 9, 8, 0],
       [4, 9, 7, 8, 9]])

In [8]:
np.shape(a)

(3, 5)

In [9]:
np.transpose(a)

array([[1, 5, 4],
       [2, 7, 9],
       [3, 9, 7],
       [4, 8, 8],
       [5, 0, 9]])

In [ ]:
x = 100

In [29]:
a = np.array([
    [1,2,3,4,5],
    [5,7,8,8,0],
    [4,9,7,8,9]
    ])

numpy.ndarray

In [30]:
b = np.array([[1, 5, 4],
       [2, 7, 9],
       [3, 9, 7],
       [4, 8, 8],
       [5, 0, 9]])
b

array([[1, 5, 4],
       [2, 7, 9],
       [3, 9, 7],
       [4, 8, 8],
       [5, 0, 9]])

In [31]:
a*b

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [32]:
np.dot(a,b)

array([[ 55,  78, 120],
       [ 75, 210, 203],
       [120, 210, 291]])

In [11]:
np.transpose(b)

array([1, 5, 6, 8, 9])

In [20]:
a + b

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [21]:
d = np.array([
    [1,2,3,4,5],
    [5,7,9,8,0],
    [4,9,7,8,9]
    ])

e = np.array([
    [1,5,4,5,9],
    [2,7,9,7,6],
    [3,9,7,4,7]
    ])
d+e

array([[ 2,  7,  7,  9, 14],
       [ 7, 14, 18, 15,  6],
       [ 7, 18, 14, 12, 16]])

In [24]:
d = np.array([
    [1,2,3,4,5],
    [5,7,9,8,0],
    [4,9,7,8,9]
    ])

e = np.array([
    [1,5,4,5,9],
    [2,7,9,7,6],
    [3,9,7,4,7]
    ])
d*2

array([[ 2,  4,  6,  8, 10],
       [10, 14, 18, 16,  0],
       [ 8, 18, 14, 16, 18]])

In [27]:
d = np.array([
    [1,2,3,4,5],
    [5,7,9,8,0],
    [4,9,7,8,9]
    ])

e = np.array([
    [1,5,4,5,9],
    [2,7,9,7,6],
    [3,9,7,4,7]
    ])
d*e

array([[ 1, 10, 12, 20, 45],
       [10, 49, 81, 56,  0],
       [12, 81, 49, 32, 63]])

In [33]:
d = np.array([
    [1,2,3,4,5],
    [5,7,9,8,0],
    [4,9,7,8,9]
    ])
np.linalg.inv(d)

LinAlgError: Last 2 dimensions of the array must be square

In [37]:
f = np.array([[ 3, -5],
              [-1,  2]])
f

array([[ 3, -5],
       [-1,  2]])

In [40]:
f_inv = np.linalg.inv(f)
f_inv

array([[2., 5.],
       [1., 3.]])

In [41]:
np.dot(f,f_inv)

array([[1., 0.],
       [0., 1.]])

# 単位行列

In [42]:
aaa = np.array([
    [1,0,0,0,0],
    [0,1,0,0,0],
    [0,0,1,0,0],
    [0,0,0,1,0],
    [0,0,0,0,1]
])
aaa

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [43]:
np.dot(d,aaa)

array([[1, 2, 3, 4, 5],
       [5, 7, 9, 8, 0],
       [4, 9, 7, 8, 9]])

In [44]:
d

array([[1, 2, 3, 4, 5],
       [5, 7, 9, 8, 0],
       [4, 9, 7, 8, 9]])

# 行列式

In [45]:
np.linalg.det(f)

1.0000000000000004

# aaa

# Pandasを使ったCSVの読み込み

## pandasのインポート

In [48]:
import pandas as pd

In [50]:
pd.read_csv("AuditLog_2020-07-28_2020-08-03.csv")

CreationDate                                 UserIds  \
0      2020-08-03T05:57:22.0000000Z  arq-member@androbotics.onmicrosoft.com   
1      2020-08-03T06:04:17.0000000Z  arn-member@androbotics.onmicrosoft.com   
2      2020-08-03T06:04:17.0000000Z  arn-member@androbotics.onmicrosoft.com   
3      2020-08-03T06:19:47.0000000Z                  s.ida@ml.androbo.co.jp   
4      2020-08-03T06:19:58.0000000Z                  s.ida@ml.androbo.co.jp   
...                             ...                                     ...   
30821  2020-07-28T22:49:03.0000000Z  aro-member@androbotics.onmicrosoft.com   
30822  2020-07-28T22:49:03.0000000Z  aro-member@androbotics.onmicrosoft.com   
30823  2020-07-28T15:20:15.0000000Z                          app@sharepoint   
30824  2020-07-28T15:26:36.0000000Z                          app@sharepoint   
30825  2020-07-28T15:28:21.0000000Z                          app@sharepoint   

                 Operations                                          AuditData  
0              UserLoggedIn  {"CreationTime":"2020-08-03T05:57:22","Id":"35...  
1              UserLoggedIn  {"CreationTime":"2020-08-03T06:04:17","Id":"4e...  
2              UserLoggedIn  {"CreationTime":"2020-08-03T06:04:17","Id":"9e...  
3      FileSyncUploadedFull  {"CreationTime":"2020-08-03T06:19:47","Id":"f0...  
4               FileRenamed  {"CreationTime":"2020-08-03T06:19:58","Id":"7c...  
...                     ...                                                ...  
30821       CompanyLinkUsed  {"CreationTime":"2020-07-28T22:49:03","Id":"d7...  
30822          FileAccessed  {"CreationTime":"2020-07-28T22:49:03","Id":"62...  
30823          FileAccessed  {"CreationTime":"2020-07-28T15:20:15","Id":"6c...  
30824          FileAccessed  {"CreationTime":"2020-07-28T15:26:36","Id":"f7...  
30825          FileAccessed  {"CreationTime":"2020-07-28T15:28:21","Id":"67...  

[30826 rows x 4 columns]

In [54]:
pd.read_csv(r"C:\Users\K_androbo\Desktop\AuditLog_2020-07-28_2020-08-03.csv")

CreationDate                                 UserIds  \
0      2020-08-03T05:57:22.0000000Z  arq-member@androbotics.onmicrosoft.com   
1      2020-08-03T06:04:17.0000000Z  arn-member@androbotics.onmicrosoft.com   
2      2020-08-03T06:04:17.0000000Z  arn-member@androbotics.onmicrosoft.com   
3      2020-08-03T06:19:47.0000000Z                  s.ida@ml.androbo.co.jp   
4      2020-08-03T06:19:58.0000000Z                  s.ida@ml.androbo.co.jp   
...                             ...                                     ...   
30821  2020-07-28T22:49:03.0000000Z  aro-member@androbotics.onmicrosoft.com   
30822  2020-07-28T22:49:03.0000000Z  aro-member@androbotics.onmicrosoft.com   
30823  2020-07-28T15:20:15.0000000Z                          app@sharepoint   
30824  2020-07-28T15:26:36.0000000Z                          app@sharepoint   
30825  2020-07-28T15:28:21.0000000Z                          app@sharepoint   

                 Operations                                          AuditData  
0              UserLoggedIn  {"CreationTime":"2020-08-03T05:57:22","Id":"35...  
1              UserLoggedIn  {"CreationTime":"2020-08-03T06:04:17","Id":"4e...  
2              UserLoggedIn  {"CreationTime":"2020-08-03T06:04:17","Id":"9e...  
3      FileSyncUploadedFull  {"CreationTime":"2020-08-03T06:19:47","Id":"f0...  
4               FileRenamed  {"CreationTime":"2020-08-03T06:19:58","Id":"7c...  
...                     ...                                                ...  
30821       CompanyLinkUsed  {"CreationTime":"2020-07-28T22:49:03","Id":"d7...  
30822          FileAccessed  {"CreationTime":"2020-07-28T22:49:03","Id":"62...  
30823          FileAccessed  {"CreationTime":"2020-07-28T15:20:15","Id":"6c...  
30824          FileAccessed  {"CreationTime":"2020-07-28T15:26:36","Id":"f7...  
30825          FileAccessed  {"CreationTime":"2020-07-28T15:28:21","Id":"67...  

[30826 rows x 4 columns]