# 行と列要素を作成し計算してみる

### npライブラリを使って行と列要素を作成

In [1]:
import numpy as np

In [16]:
kakezan = np.array([
    [10,8,-8,1000],
    [-4,8,15,0],
    [3,5,9,10]
    ])
kakezan
# ３行４列

array([[  10,    8,   -8, 1000],
       [  -4,    8,   15,    0],
       [   3,    5,    9,   10]])

In [17]:
a = -19
a

-19

In [18]:
b = [5,-9,10]
b

[5, -9, 10]

In [29]:
tui = ([
    [a,5,105],
    b,
    [2,-56,7],
    [1,2,3]
])
tui
# ４行3列

[[-19, 5, 105], [5, -9, 10], [2, -56, 7], [1, 2, 3]]

In [30]:
tui_2 = np.array(tui)
tui_2

array([[-19,   5, 105],
       [  5,  -9,  10],
       [  2, -56,   7],
       [  1,   2,   3]])

In [31]:
type(kakezan)

numpy.ndarray

In [32]:
type(tui_2)

numpy.ndarray

In [33]:
kakezan*tui_2

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [34]:
np.dot(kakezan,tui_2)

array([[ 834, 2426, 4074],
       [ 146, -932, -235],
       [  -4, -514,  458]])

## いぇい